import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Body from "../components/Body";
import { useAccount } from 'wagmi'



export default function Home() {
  const { isConnected } = useAccount()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        {isConnected ? (
          <Body/>
        ) : (
          <p>Please connect to a Wallet</p>
        )}
      </div>
    </div>
  );
}
