import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import AccountManagment from "../components/AccountManagment";
import SudokuBoard from "../components/SudokuBoard";
import { useAccount } from 'wagmi'

export default function Home() {
  const { address, isConnected } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <SudokuBoard />
        {isConnected ? (
          <AccountManagment />
        ) : (
          <div>Please connect to a Wallet</div>
        )}
      </div>
    </div>
  );
}
//