[package]
name = "back_end"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigint = "4.4.3"
cap = "0.1.1"
num-bigint = "0.4.3"
num-traits = "0.2.15"
priority-queue = "1.3.0"
queues = "1.1.0"
